### ISSUE TITLE
Configure i18next directly, not in provider

### ISSUE THREAD

**Issue by allanrh** [i18next/ng-i18next#101]
Hi, I'm using i18next in an Appery.io app, which prevents me from being able to configure i18n via the ng-i18next provider. Is there a way for me to use this ng-i18next Angular module and configure i18n via some kind of direct access to the i18n component, without needing to configure the provider? thanks

**Comment by archer96** [comment]
At the moment, no. Sorry :/

But feel free to create a pull request :)

Regards,
Andre

**Comment by anwalkers** [comment]
This approach is implemented in this PR: https://github.com/i18next/ng-i18next/pull/117

**Comment by anwalkers** [comment]
version 1.0.0 of ng-i18next has taken this approach. Please review upgrade instructions and examples for more details.
