### ISSUE TITLE
Search for a new maintainer

### ISSUE THREAD

**Issue by archer96** [i18next/ng-i18next#104]
I (developer of `ng-i18next`) am in search for a new maintainer of this repository.

### Why? ###
I don't use `i18next` in current private projects and have other projects that need more attention. 
I don't have time to fix bugs or add support for the new `i18next` version or `angular` v2.

### What needs to be done? ###
There are about 13 open issues at the moment of which many have to be fixed in order for `ng-i18next` to work properly.

There are also another few things to do:

 - add support for `angular` v2
 - add support for `i18next` v2
 - fix known bugs
 - create more tests

If you think that you are able to be the new maintainer, let me know.

Regards,
Andre

**Comment by anwalkers** [comment]
I'll take it on Andre...

**Comment by archer96** [comment]
I think you have done a great job with the [i18next-v2 branch](https://github.com/i18next/ng-i18next/tree/i18next-v2). :+1: 
There are still a few things that need to be done (e.g. [README](https://github.com/i18next/ng-i18next/tree/i18next-v2#supported-browsers) or the [CHANGELOG](https://github.com/i18next/ng-i18next/blob/i18next-v2/CHANGELOG.md)) but everything looks promising.

I'd be glad to make you the maintainer of this project. :smiley: 
If @jamuhl agrees on this, he can make you the new maintainer.

**Comment by anwalkers** [comment]
Okay, I will try to tackle the readme and changelog. The integration against our project has gone well. I will carve out some time to update these soon.

**Comment by jamuhl** [comment]
@anwalkers @archer96 for sure...what should i have against it...happy to see that the ng-i18next will be in good hands.

**Comment by anwalkers** [comment]
@jamuhl @archer96 Anything I need to do to take on the maintainer role?

**Comment by jamuhl** [comment]
@anwalkers i innvited you to the admin group of this repo...if this is published on npm (i guess) someone needs to give you publish or ownership there

**Comment by anwalkers** [comment]
@jamuhl @archer96 Seems like I can push changes and add tags. I have upgraded master to 1.0.0 and merged in my changes.
