### ISSUE TITLE
Node.js: 0.1 builds are failing

### ISSUE THREAD

**Issue by nsand** [i18next/ng-i18next#107]
I noticed this after my last PR, but it looks like the Node.js: 0.1 builds are failing due to gulp-karma's dependency on `karma@>=0.10 <=0.13`. According to the maintainer, https://github.com/lazd/gulp-karma is deprecated, and Karma should be used directly. So this might be a good opportunity to move away from a deprecated module and fixing a failing build.

**Comment by archer96** [comment]
Thanks again :) :+1:
