### ISSUE TITLE
Broken links to i18next.com in ReadMe

### ISSUE THREAD

**Issue by NumEricR** [i18next/ng-i18next#118]
Hi
I've noticed some broken links in ReadMe:

1. "nested translations ($t('hello'); see [i18next documentation](http://i18next.com/pages/doc_features.html))" 
Maybe this link should go to http://i18next.com/translate/nesting

2. "For more options visit the [i18next documentation](http://i18next.com/pages/doc_init.html)." 
And I think this one should redirect users to http://i18next.com/docs/options

**Comment by anwalkers** [comment]
Fixed
