### ISSUE TITLE
Exporting the module name

### ISSUE THREAD

**Issue by peebeebee** [i18next/ng-i18next#121]
To easily import the whole module in ES6, there should be something along the lines of
`export default 'jm.i18next'` in the module.

Then you can do the following with a package manager such as JSPM:
```
import ngI18next from 'i18next/ng-i18next';
angular.module(myModule, [ngI18next]);
```
So very loosely coupled.

Sidequestion: Why is the only thing that is exported right now the I18nProvider?

**Comment by anwalkers** [comment]
The provider should not be exported.

I will export 'jm.i18next'

I will submit a patch.

**Comment by anwalkers** [comment]
Now exports `'jm.i18next'` to support JSPM and WebPack

```
angular.module('jm.i18next', ['ng', 'ngSanitize'])
    .provider('$i18next', I18nProvider)
    .directive('ngI18next', I18nDirective.factory())
    .directive('boI18next', I18nBindOnceDirective.factory())
    .controller('NgI18nextController', I18nDirectiveController)
    .filter('i18next', I18nFilter.factory());
var provider = 'jm.i18next';

return provider;
```
