### ISSUE TITLE
Regression: translation isn't re-rendered when option from scope value changes

### ISSUE THREAD

**Issue by bloveridge** [i18next/ng-i18next#122]
I finally took the plunge today to migrate my rather extensive app from `0.5.4` to `1.0.2`. After getting my custom plurals fixed up, it looked like everything was working fine, but then I noticed a subtle bug: when passing data from a scope variable in as an option using the directive, the value is not being re-rendered. It worked fine in `0.5.4` but does not work anymore on `1.0.2`. Below are some test cases that show the behavior.

I tried digging into the code a bit to find the issue, but I haven't been able to figure it out yet. As far as I'm aware, this issue is the only thing preventing me from getting my `i18next` / `ng-i18next` toolchain fully updated.

```js
//
// Test cases for v0.5.4 -- everything passes
//
it('should replace "__name__" in the translation string with scope variable', function () {
	inject(function ($rootScope, $compile) {
		$rootScope.name = 'Wax';
		var c = $compile('<p ng-i18next="[i18next]({name:name})helloName"></p>')($rootScope);
		$rootScope.$apply();
		expect(c.text()).toEqual('Herzlich Willkommen, Wax!');
	});
});

it('should update "__name__" in the translation string when scope variable changes', function () {
	inject(function ($rootScope, $compile) {
		$rootScope.name = 'Wax';
		var c = $compile('<p ng-i18next="[i18next]({name:name})helloName"></p>')($rootScope);
		$rootScope.$apply();
		expect(c.text()).toEqual('Herzlich Willkommen, Wax!');
		$rootScope.name = 'Wayne';
		$rootScope.$apply();
		expect(c.text()).toEqual('Herzlich Willkommen, Wayne!');
	});
});
```

```js
//
// Test cases for v1.0.2 -- functionally identical, but final expectation fails.
//
it('should replace "{{name}}" in the translation string with scope variable', function () {
	$rootScope.name = "Wax";
	var c = $compile('<p ng-i18next="[i18next]({name: name})helloName"></p>')($rootScope);
	$rootScope.$apply();
	expect(c.text()).toEqual('Herzlich Willkommen, Wax!');
});

it('should update "{{name}}" in the translation string when scope variable changes', function () {
	$rootScope.name = "Wax";
	var c = $compile('<p ng-i18next="[i18next]({name: name})helloName"></p>')($rootScope);
	$rootScope.$apply();
	expect(c.text()).toEqual('Herzlich Willkommen, Wax!');
	$rootScope.name = "Wayne";
	$rootScope.$apply();
	expect(c.text()).toEqual('Herzlich Willkommen, Wayne!');
});
```

**Comment by anwalkers** [comment]
@bloveridge Thanks for the effort! I will review tomorrow

**Comment by AleRob90** [comment]
Hi, i am having the same issue in version 1.0.3.
I have created a custom directive with scope: {data: '='} and when i'm changing it from outside, directive show proper data, but <div ng-i18next>[html]data</div> doesn't update:(. Right now my only option is to delete and recreate the directive.
