### ISSUE TITLE
window.i18next is undefined when using ng-i18next and jspm 0.17

### ISSUE THREAD

**Issue by awk** [i18next/ng-i18next#124]
Using jspm I did

`
jspm install i18next npm:ng-i18next
`

My application imports the `ng-i18next` component, however the load fails because `I18nProvider` doesn't have `window.i18next` loaded.

It looks like the preferred installation of i18next is a commonjs module, however ng-i18next expects the i18next symbol in the global/window namespace.

Should ng-i18next actually be a commonjs module which declares it's dependency on i18next?

**Comment by anwalkers** [comment]
Definitely a bug.

**Comment by anwalkers** [comment]
This is fixed in v1.0.4
