### ISSUE TITLE
Question: How to pass options to ng-i18next filter?

### ISSUE THREAD

**Issue by slichte** [i18next/ng-i18next#125]
Hey!
I have a question about the ng-18next filter.
How to pass options to the filter, i.e. what would this call look like as a filter?

`<p ng-i18next="[html]hello"></p>`
`<p>{{'hello' | i18next:??? }}</p>`

And about the directive: how can I pass objects for placeholders? Like this?
`<p ng-i18next="[html](objectFromScope)hello"></p>`

Thanks a lot for your help!

**Comment by anwalkers** [comment]
Does this from the examples code help any? https://github.com/i18next/ng-i18next/blob/master/examples/filter/passingOptions.html

You can specify the language and do interpolation. See the i18next documentation for more details. http://i18next.com/translate/interpolation/

**Comment by slichte** [comment]
Hi anwalkers,

Thanks for your reply. I just digged through the code and found the following lines in I18nDirectiveController's render method:

`if (parsedKey.options.attr === 'html') {
                    this.$element.empty().append(localizedString);
                    /*
                     * Now compile the content of the element and bind the variables to
                     * the scope
                     */
                    this.$compile(this.$element.contents())(this.$scope);
                    return;
                }`

Those lines don't exist in I18nFilter and so I don't think it's possible to use translation strings with HTML content in connection with the filter. Maybe in the next version :). Thanks & have a nice day.
