### ISSUE TITLE
Example of passing interpolated values to directive

### ISSUE THREAD

**Issue by httpete** [i18next/ng-i18next#127]
Hi,

I am struggling to see an example of a very common use

//string is "About {productName}

	<h3 ng-i18next="ns:aboutProduct({ productName: 'pete' }}"></h3>

how do I pass the object containing key value pairs for interpolation? Thank you.

**Comment by anwalkers** [comment]
Have you tried...

`<h3 ng-i18next="[i18next]({ productName: 'pete' })ns:aboutProduct"></h3>`
