### ISSUE TITLE
interpolation issue(use default value, when I need key => value)

### ISSUE THREAD

**Issue by hernimen** [i18next/ng-i18next#128]
```
	get originRequired(){
			return this.$i18next.t('event-form.' + this.event.type + '.originRequired', {originLabel: this.originLabel})
		}
```

I am getting missing key altought it's translating the default value. I need this interpolation to be the key and value and the i18next web page it's not working.

**Comment by jamuhl** [comment]
try www.i18next.com that should work (i18next.com is still unstable updating forwarding)
