### ISSUE TITLE
HTML tags are not sanitized properly when passed as an option

### ISSUE THREAD

**Issue by chris-miaskowski** [i18next/ng-i18next#133]
Hi, I wanted to say the library is great and it helps me a lot with localising the app I'm working on.
I have, however, stumbled across a problem I can't find a workaround for.
I'm working on a project that's using Angular 1.2.8 and trying to translate this string:

`<h3 ng-i18next="[html:i18next]({ small_start: '<small>', small_end: '</small>' })some-key"></h3>`

where:

`"some-key": "text outside {{small_start}}small text?{{small_end}}"`

renders on the page as (literally):

`text outside <small></small>small text?`

I would greatly appreciate any help from your end.

**Comment by miluoshi** [comment]
You forgot to [unescape](https://www.i18next.com/interpolation.html#unescape) your placeholders in the translation string, like this: `"some-key": "text outside {{- small_start}}small text?{{-
 small_end}}"`
