### ISSUE TITLE
i18next interpolation service

### ISSUE THREAD

**Issue by PascalPrecht** [i18next/ng-i18next#17]
Hey @archer96, looks like you build [angular-translate](http://github.com/PascalPrecht/angular-translate)'s little brother :)

I'll release version 1.0 very soonish and with the release of 1.0 I introduce pluggable interpolation services. About about building an interpolation service extension for i18next?

**Comment by jmls** [comment]
did this ever get written ?

**Comment by archer96** [comment]
@jmls No :(
I actually wrote some code but never finished it and now it's already been two years since this issue was opened...
I don't think that I will create an interpolation service for `angular-translate` anymore. :/
