### ISSUE TITLE
Both filter and directive flash Key in DOM before replacing it with translated Value

### ISSUE THREAD

**Issue by MasterKale** [i18next/ng-i18next#73]
Is there a way to prevent the i18next key from being displayed on-screen for a second before it's replaced with its corresponding value? 

For example, I tried using both the filter and the directive in the header of my layout:

```
{
    "app_name" : "App Name"
}
<a class="navbar-brand" href="#/">{{ "app_name" | i18next }}</a>
<a class="navbar-brand" href="#/" ng-i18next="app_name"></a>
```

Regardless of which of those I use, when I reload my page "app_name" appears for a split second before i18next does its magic and replaces it with the properly translated "App Name". Is there something else I need to do to prevent this from happening?

**Comment by MasterKale** [comment]
And of course after posting this I re-read the project's README and saw 'defaultLoadingValue'. That at least prevents the Key from being displayed, but now I'm curious if there's a way to delay page load until all of the values have been translated. Right now the site name pops into existence a split-second after the page has loaded, but it's noticeable enough. Maybe I should just throw up a load screen for a second to let everything settle into place before allowing anyone to interact with the page...

**Comment by archer96** [comment]
Well, you could try something like this:

https://github.com/i18next/ng-i18next/blob/master/examples/directive/directive.js#L32-L39
https://github.com/i18next/ng-i18next/blob/master/examples/directive/i18nextCloak.html#L34-L35

This way you could create a loading screen. :)

Regards,
Andre

**Comment by archer96** [comment]
Due to inactivity this will be closed. You are free to reopen this issue.

Regards,
Andre
