### ISSUE TITLE
Performance degradation since release 0.3.5

### ISSUE THREAD

**Issue by lcalvy** [i18next/ng-i18next#75]
Hi, 

Could you gave me informations about this patch 
https://github.com/i18next/ng-i18next/commit/1a73ec182fe80e7803535c826dc56dfa08326d5c#diff-ebf3979692cdbbeda460cd60ac620a9d

Since modification below performance on our site is really degraded.

![image](https://cloud.githubusercontent.com/assets/937507/6184071/896d029c-b35d-11e4-8f36-2f97fd127089.png)

 

__Init time with version 0.3.5__
![image](https://cloud.githubusercontent.com/assets/937507/6184078/abe4d084-b35d-11e4-99e9-a8ea27c3e1ec.png)

__Init tile with version 0.3.4__
![image](https://cloud.githubusercontent.com/assets/937507/6184086/bd8b5e84-b35d-11e4-90ab-ffdc1106b9f3.png)

As you can see scripting part is 6 seconds longer.

After some investigations, I found that passing the full merge option to translate method trigger in i18next a lot of processing.
Internal method applyReplacement is now executed 58181 times versus 273 times on previous version. 
 
It's not really a bug of ng-i18next but I need to understand what your patch has fixed.

Regards

**Comment by AleksueiR** [comment]
:+1:

**Comment by anwalkers** [comment]
Would be interested if the 1.0.0 has fixed any of this...
