### ISSUE TITLE
Add mention of angular-sanitize in readme.md

### ISSUE THREAD

**Issue by dantix** [i18next/ng-i18next#87]
$SUBJ

**Comment by archer96** [comment]
Done: https://github.com/i18next/ng-i18next/blob/master/README.md#usage
Also updated all example (see https://github.com/i18next/ng-i18next/commit/464820b2ee3880612ef0dc0357e0a1da8080c470 ).

Thank you :+1: 
Totally forgot about this.


Regards,
Andre
