### ISSUE TITLE
Upgrade to 0.5.0: Senseless console.log call

### ISSUE THREAD

**Issue by mwager** [i18next/ng-i18next#93]
Hey there,

after upgrading to 0.5.0 we experience a console.log call in our app:

```
[ng-i18next] i18next error: null
```

Here you just check for 'undefined' but the error is null: (typeof null === 'object')

https://github.com/i18next/ng-i18next/blob/master/releases/v0.5.0/ng-i18next.js#L53

and the callback gets called like cb(null, ...)

**Comment by archer96** [comment]
Yeah,.. New version of i18next. Will fix this as soon as possible.
Thanks for reporting. :+1:
