### ISSUE TITLE
Compatibility issue with latest version

### ISSUE THREAD

**Issue by radjivC** [i18next/ng-i18next#95]
Hi, 

After an update of ng-i18next to 0.5.1 (with a dependencies of 1.10.0 of i18next), 
My client angular side didn't find my locales files.

I made some investigations and 
if I use an older version of the dependencies  i18next like the 1.7.4 everything come back alright.
but if I use 1.10.0 it won't work.

Doesn't matter the version of ng-i18next, looks like the problem from of a compatibility with i18next lastest version.

Thank you for your help!

**Comment by archer96** [comment]
I tested it with follwing setup:

- `Angular` `v1.4.2`
- `i18next` `v1.10.2`
- `ng-i18next` `v0.5.1`

I can't reproduce this issue. Could you post the messages/errors you get (from console)? :)

Regards,
Andre

**Comment by radjivC** [comment]
I dont have any error message.

I have initialize my client side like that:
`````
angular.module('myapp').config(['$i18nextProvider',
    function($i18nextProvider) {
        'use strict';
        $i18nextProvider.options = {
            lng: 'fr',
            supportedLngs: ['fr', 'en'],
            useLocalStorage: false,
            resGetPath: 'locales/resources.json?lng=__lng__&ns=__ns__',
            dynamicLoad: true,
            ns: {
                namespaces: ['global', 'licenses', 'generator', 'billing', 'graphs'],
            },
        };
    },
]);
`````
