### ISSUE TITLE
Question: Extracting translations.

### ISSUE THREAD

**Issue by antwan1986** [i18next/ng-i18next#97]
Hey,

I'm wondering how users of this package are maintaining their POT files. Are people doing it all manually or is there an existing tool that can look through JS / Template files and pick out the angular wrapped translations, and form a POT file?

Any help on this matter would be greatly appreciated!

Thanks,
Anthony

**Comment by archer96** [comment]
I do this manually ;)
But have a look at this project: https://github.com/i18next/i18next-parser

>  "A simple command line and gulp plugin that lets you parse your code and extract the translations keys in it."

**Comment by antwan1986** [comment]
Thanks for the information!

**Comment by archer96** [comment]
I'm glad to help you ;)
