### ISSUE TITLE
data-i18n vs data-i18next

### ISSUE THREAD

**Issue by jmls** [i18next/ng-i18next#98]
on the http://i18next.com/ website, they show an example like this

```html
<li><a href="#" data-i18n="nav.home"></a></li>
```

whereas with ng-i18next it is specified as
```html
<li><a href="#" ng-i18next="nav.home"></a></li>
```
can I use data-i18n as well ?

**Comment by archer96** [comment]
Currently you can't. See: https://github.com/i18next/ng-i18next/blob/master/src/directive/directive.js#L1

I've choosen `ng-i18next`, so that there won't be any collisions in the future if `angular.js`  implements their own translation directive.

Regards,
Andre

**Comment by archer96** [comment]
I'll close this issue due to inactivity.

Fell free to reopen this issue.

Regards,
Andre
